# Generated by Django 5.2.7 on 2025-10-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="employer_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("under_review", "Under Review"),
                    ("shortlisted", "Shortlisted"),
                    ("interview", "Interview Scheduled"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
    ]
