version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             gunicorn job_portal.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    environment:
      - DEBUG=False
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    restart: unless-stopped

  # Note: For Render, we'll use their managed PostgreSQL
  # db service is removed since Render provides database